### PR TITLE
Fix conversion factor in timer metrics

### PR DESCRIPTION
**Pull request by Firehed**
Currently, timers emit metrics that are off by a factor of 1000 due to an incorrect conversion of nanoseconds to milliseconds. This fixes that error, and adds several test cases to cover the `record{unit}` methods.

Simplified sample failure:
```swift
import Metrics
import StatsdClient

let client = StatsdClient(host: "127.0.0.1", port: 8125)
MetricsSystem.bootstrap(client)
let timer = Timer(label: "com.example.duration")
timer.recordMilliseconds(1.234)
```
In a UDP dump to show what the statsd server currently receives:
```
com.example.duration:1234|ms
```
This changes to:
```
com.example.duration:1.234|ms
```

*Edit*: added detail on UDP output

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
thanks @Firehed, great catch. could you please run `swiftformat .` to get CI passing

**Comment by Firehed** [comment]
@tomerd Should be resolved now. My local `swift format` wouldn't pick up on the issue, so I just applied the diff from CI by hand.

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
sry @Firehed but CI is now failing on missing linux tests, please run `./scripts/generate_linux_tests` as well. to make sure everything is ready you can run `./scripts/sanity`

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by Firehed** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by tomerd — APPROVED** [review]
thanks so much @Firehed

**Comment by tomerd** [comment]
@Firehed  this is now in 1.0.0-alpha.2

**Pull request merged**
